### ISSUE TITLE
There are too many levels of forum replies in the UI

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/spacedecentral-network#28]
It looks like the level of replies just keeps growing.

https://spacedecentral.net/forum/posts/synergy-with-moon-village-association-and-others

This makes it difficult to read on mobile. Can we limit it to 3 levels? in the above link, I see 5 levels of replies. The final level should be like the one you see "Hello Jason! Happy to hear you are interested "

The "Reply" link should still show up. It's just in the UI, we should not indent it any further than 3 levels of replies.

Acceptance testing:
Need to make sure this looks good on mobile

**Comment by ottodevs** [comment]
The problem is harder than I thought.

I initially thought it only was a CSS problem, but when I went deeper into the code I discovered a serious bug.

![image](https://user-images.githubusercontent.com/5030059/38850861-9cbb110c-4213-11e8-8fd2-0020b233a8b4.png)

In my screenshot all sub-replies are actually nested within each other, but they are perfectly aligned in the 3rd level, so I would say the issue was fixed, but actually didn't make any changes...

The real problem is that all the sub-replies in my screenshot, were created without refreshing the page, so in the database they all were assigned as the 2nd level reply sub-replies, that is why they appear aligned. The field that is causing the problem is "replicable_id"

When I refresh the page and try to make, for example, another 4th level sub-reply to the 3rd level reply, then it goes to the right place and gets aligned correctly, with the 4th level indentation.

So this error must be fixed before trying to mess with nesting levels, because it could affect the actual stored data, as some sub-replies in the forum, may be currently pointing to wrong parent replies.
